export interface CountryOption {
  code: string; // Phone prefix, e.g., +93
  country: string; // Full name, e.g., Afghanistan
  iso: string; // Unique lowercase ID for flags, e.g., af
}

export const countryOptions: CountryOption[] = [
  { country: "Afghanistan", iso: "af", code: "+93" },
  { country: "Aland Islands", iso: "ax", code: "+358" },
  { country: "Albania", iso: "al", code: "+355" },
  { country: "Algeria", iso: "dz", code: "+213" },
  { country: "American Samoa", iso: "as", code: "+1" },
  { country: "Andorra", iso: "ad", code: "+376" },
  { country: "Angola", iso: "ao", code: "+244" },
  { country: "Anguilla", iso: "ai", code: "+1264" },
  { country: "Antarctica", iso: "aq", code: "+672" },
  { country: "Antigua and Barbuda", iso: "ag", code: "+1" },
  { country: "Argentina", iso: "ar", code: "+54" },
  { country: "Armenia", iso: "am", code: "+374" },
  { country: "Aruba", iso: "aw", code: "+297" },
  { country: "Australia", iso: "au", code: "+61" },
  { country: "Austria", iso: "at", code: "+43" },
  { country: "Azerbaijan", iso: "az", code: "+994" },
  { country: "Bahamas", iso: "bs", code: "+1" },
  { country: "Bahrain", iso: "bh", code: "+973" },
  { country: "Bangladesh", iso: "bd", code: "+880" },
  { country: "Barbados", iso: "bb", code: "+1" },
  { country: "Belarus", iso: "by", code: "+375" },
  { country: "Belgium", iso: "be", code: "+32" },
  { country: "Belize", iso: "bz", code: "+501" },
  { country: "Benin", iso: "bj", code: "+229" },
  { country: "Bermuda", iso: "bm", code: "+1" },
  { country: "Bhutan", iso: "bt", code: "+975" },
  { country: "Bolivia", iso: "bo", code: "+591" },
  { country: "Bonaire, Saint Eustatius and Saba", iso: "bq", code: "+599" },
  { country: "Bosnia and Herzegovina", iso: "ba", code: "+387" },
  { country: "Botswana", iso: "bw", code: "+267" },
  { country: "Bouvet Island", iso: "bv", code: "+47" },
  { country: "Brazil", iso: "br", code: "+55" },
  { country: "British Indian Ocean Territory", iso: "io", code: "+246" },
  { country: "British Virgin Islands", iso: "vg", code: "+1" },
  { country: "Brunei", iso: "bn", code: "+673" },
  { country: "Bulgaria", iso: "bg", code: "+359" },
  { country: "Burkina Faso", iso: "bf", code: "+226" },
  { country: "Burundi", iso: "bi", code: "+257" },
  { country: "Cambodia", iso: "kh", code: "+855" },
  { country: "Cameroon", iso: "cm", code: "+237" },
  { country: "Canada", iso: "ca", code: "+1" },
  { country: "Cape Verde", iso: "cv", code: "+238" },
  { country: "Cayman Islands", iso: "ky", code: "+1" },
  { country: "Central African Republic", iso: "cf", code: "+236" },
  { country: "Chad", iso: "td", code: "+235" },
  { country: "Chile", iso: "cl", code: "+56" },
  { country: "China", iso: "cn", code: "+86" },
  { country: "Christmas Island", iso: "cx", code: "+61" },
  { country: "Cocos Islands", iso: "cc", code: "+61" },
  { country: "Colombia", iso: "co", code: "+57" },
  { country: "Comoros", iso: "km", code: "+269" },
  { country: "Cook Islands", iso: "ck", code: "+682" },
  { country: "Costa Rica", iso: "cr", code: "+506" },
  { country: "Croatia", iso: "hr", code: "+385" },
  { country: "Cuba", iso: "cu", code: "+53" },
  { country: "Curacao", iso: "cw", code: "+599" },
  { country: "Cyprus", iso: "cy", code: "+357" },
  { country: "Czech Republic", iso: "cz", code: "+420" },
  { country: "Democratic Republic of the Congo", iso: "cd", code: "+243" },
  { country: "Denmark", iso: "dk", code: "+45" },
  { country: "Djibouti", iso: "dj", code: "+253" },
  { country: "Dominica", iso: "dm", code: "+1" },
  { country: "Dominican Republic", iso: "do", code: "+1" },
  { country: "East Timor", iso: "tl", code: "+670" },
  { country: "Ecuador", iso: "ec", code: "+593" },
  { country: "Egypt", iso: "eg", code: "+20" },
  { country: "El Salvador", iso: "sv", code: "+503" },
  { country: "Equatorial Guinea", iso: "gq", code: "+240" },
  { country: "Eritrea", iso: "er", code: "+291" },
  { country: "Estonia", iso: "ee", code: "+372" },
  { country: "Ethiopia", iso: "et", code: "+251" },
  { country: "Falkland Islands", iso: "fk", code: "+500" },
  { country: "Faroe Islands", iso: "fo", code: "+298" },
  { country: "Fiji", iso: "fj", code: "+679" },
  { country: "Finland", iso: "fi", code: "+358" },
  { country: "France", iso: "fr", code: "+33" },
  { country: "French Guiana", iso: "gf", code: "+594" },
  { country: "French Polynesia", iso: "pf", code: "+689" },
  { country: "French Southern Territories", iso: "tf", code: "+262" },
  { country: "Gabon", iso: "ga", code: "+241" },
  { country: "Gambia", iso: "gm", code: "+220" },
  { country: "Georgia", iso: "ge", code: "+995" },
  { country: "Germany", iso: "de", code: "+49" },
  { country: "Ghana", iso: "gh", code: "+233" },
  { country: "Gibraltar", iso: "gi", code: "+350" },
  { country: "Greece", iso: "gr", code: "+30" },
  { country: "Greenland", iso: "gl", code: "+299" },
  { country: "Grenada", iso: "gd", code: "+1" },
  { country: "Guadeloupe", iso: "gp", code: "+590" },
  { country: "Guam", iso: "gu", code: "+1" },
  { country: "Guatemala", iso: "gt", code: "+502" },
  { country: "Guernsey", iso: "gg", code: "+44" },
  { country: "Guinea", iso: "gn", code: "+224" },
  { country: "Guinea-Bissau", iso: "gw", code: "+245" },
  { country: "Guyana", iso: "gy", code: "+592" },
  { country: "Haiti", iso: "ht", code: "+509" },
  { country: "Heard Island and McDonald Islands", iso: "hm", code: "" },
  { country: "Honduras", iso: "hn", code: "+504" },
  { country: "Hong Kong", iso: "hk", code: "+852" },
  { country: "Hungary", iso: "hu", code: "+36" },
  { country: "Iceland", iso: "is", code: "+354" },
  { country: "India", iso: "in", code: "+91" },
  { country: "Indonesia", iso: "id", code: "+62" },
  { country: "Iran", iso: "ir", code: "+98" },
  { country: "Iraq", iso: "iq", code: "+964" },
  { country: "Ireland", iso: "ie", code: "+353" },
  { country: "Isle of Man", iso: "im", code: "+44" },
  { country: "Israel", iso: "il", code: "+972" },
  { country: "Italy", iso: "it", code: "+39" },
  { country: "Ivory Coast", iso: "ci", code: "+225" },
  { country: "Jamaica", iso: "jm", code: "+1" },
  { country: "Japan", iso: "jp", code: "+81" },
  { country: "Jersey", iso: "je", code: "+44" },
  { country: "Jordan", iso: "jo", code: "+962" },
  { country: "Kazakhstan", iso: "kz", code: "+7" },
  { country: "Kenya", iso: "ke", code: "+254" },
  { country: "Kiribati", iso: "ki", code: "+686" },
  { country: "Kosovo", iso: "xk", code: "+383" },
  { country: "Kuwait", iso: "kw", code: "+965" },
  { country: "Kyrgyzstan", iso: "kg", code: "+996" },
  { country: "Laos", iso: "la", code: "+856" },
  { country: "Latvia", iso: "lv", code: "+371" },
  { country: "Lebanon", iso: "lb", code: "+961" },
  { country: "Lesotho", iso: "ls", code: "+266" },
  { country: "Liberia", iso: "lr", code: "+231" },
  { country: "Libya", iso: "ly", code: "+218" },
  { country: "Liechtenstein", iso: "li", code: "+423" },
  { country: "Lithuania", iso: "lt", code: "+370" },
  { country: "Luxembourg", iso: "lu", code: "+352" },
  { country: "Macao", iso: "mo", code: "+853" },
  { country: "Macedonia", iso: "mk", code: "+389" },
  { country: "Madagascar", iso: "mg", code: "+261" },
  { country: "Malawi", iso: "mw", code: "+265" },
  { country: "Malaysia", iso: "my", code: "+60" },
  { country: "Maldives", iso: "mv", code: "+960" },
  { country: "Mali", iso: "ml", code: "+223" },
  { country: "Malta", iso: "mt", code: "+356" },
  { country: "Marshall Islands", iso: "mh", code: "+692" },
  { country: "Martinique", iso: "mq", code: "+596" },
  { country: "Mauritania", iso: "mr", code: "+222" },
  { country: "Mauritius", iso: "mu", code: "+230" },
  { country: "Mayotte", iso: "yt", code: "+262" },
  { country: "Mexico", iso: "mx", code: "+52" },
  { country: "Micronesia", iso: "fm", code: "+691" },
  { country: "Moldova", iso: "md", code: "+373" },
  { country: "Monaco", iso: "mc", code: "+377" },
  { country: "Mongolia", iso: "mn", code: "+976" },
  { country: "Montenegro", iso: "me", code: "+382" },
  { country: "Montserrat", iso: "ms", code: "+1" },
  { country: "Morocco", iso: "ma", code: "+212" },
  { country: "Mozambique", iso: "mz", code: "+258" },
  { country: "Myanmar", iso: "mm", code: "+95" },
  { country: "Namibia", iso: "na", code: "+264" },
  { country: "Nauru", iso: "nr", code: "+674" },
  { country: "Nepal", iso: "np", code: "+977" },
  { country: "Netherlands", iso: "nl", code: "+31" },
  { country: "New Caledonia", iso: "nc", code: "+687" },
  { country: "New Zealand", iso: "nz", code: "+64" },
  { country: "Nicaragua", iso: "ni", code: "+505" },
  { country: "Niger", iso: "ne", code: "+227" },
  { country: "Nigeria", iso: "ng", code: "+234" },
  { country: "Niue", iso: "nu", code: "+683" },
  { country: "Norfolk Island", iso: "nf", code: "+672" },
  { country: "North Korea", iso: "kp", code: "+850" },
  { country: "Northern Mariana Islands", iso: "mp", code: "+1" },
  { country: "Norway", iso: "no", code: "+47" },
  { country: "Oman", iso: "om", code: "+968" },
  { country: "Pakistan", iso: "pk", code: "+92" },
  { country: "Palau", iso: "pw", code: "+680" },
  { country: "Palestinian Territory", iso: "ps", code: "+970" },
  { country: "Panama", iso: "pa", code: "+507" },
  { country: "Papua New Guinea", iso: "pg", code: "+675" },
  { country: "Paraguay", iso: "py", code: "+595" },
  { country: "Peru", iso: "pe", code: "+51" },
  { country: "Philippines", iso: "ph", code: "+63" },
  { country: "Pitcairn", iso: "pn", code: "+870" },
  { country: "Poland", iso: "pl", code: "+48" },
  { country: "Portugal", iso: "pt", code: "+351" },
  { country: "Puerto Rico", iso: "pr", code: "+1" },
  { country: "Qatar", iso: "qa", code: "+974" },
  { country: "Republic of the Congo", iso: "cg", code: "+242" },
  { country: "Reunion", iso: "re", code: "+262" },
  { country: "Romania", iso: "ro", code: "+40" },
  { country: "Russia", iso: "ru", code: "+7" },
  { country: "Rwanda", iso: "rw", code: "+250" },
  { country: "Saint Barthelemy", iso: "bl", code: "+590" },
  { country: "Saint Helena", iso: "sh", code: "+290" },
  { country: "Saint Kitts and Nevis", iso: "kn", code: "+1" },
  { country: "Saint Lucia", iso: "lc", code: "+1" },
  { country: "Saint Martin", iso: "mf", code: "+590" },
  { country: "Saint Pierre and Miquelon", iso: "pm", code: "+508" },
  { country: "Saint Vincent and the Grenadines", iso: "vc", code: "+1" },
  { country: "Samoa", iso: "ws", code: "+685" },
  { country: "San Marino", iso: "sm", code: "+378" },
  { country: "Sao Tome and Principe", iso: "st", code: "+239" },
  { country: "Saudi Arabia", iso: "sa", code: "+966" },
  { country: "Senegal", iso: "sn", code: "+221" },
  { country: "Serbia", iso: "rs", code: "+381" },
  { country: "Seychelles", iso: "sc", code: "+248" },
  { country: "Sierra Leone", iso: "sl", code: "+232" },
  { country: "Singapore", iso: "sg", code: "+65" },
  { country: "Sint Maarten", iso: "sx", code: "+599" },
  { country: "Slovakia", iso: "sk", code: "+421" },
  { country: "Slovenia", iso: "si", code: "+386" },
  { country: "Solomon Islands", iso: "sb", code: "+677" },
  { country: "Somalia", iso: "so", code: "+252" },
  { country: "South Africa", iso: "za", code: "+27" },
  {
    country: "South Georgia and the South Sandwich Islands",
    iso: "gs",
    code: "+500",
  },
  { country: "South Korea", iso: "kr", code: "+82" },
  { country: "South Sudan", iso: "ss", code: "+211" },
  { country: "Spain", iso: "es", code: "+34" },
  { country: "Sri Lanka", iso: "lk", code: "+94" },
  { country: "Sudan", iso: "sd", code: "+249" },
  { country: "Suriname", iso: "sr", code: "+597" },
  { country: "Svalbard and Jan Mayen", iso: "sj", code: "+47" },
  { country: "Swaziland", iso: "sz", code: "+268" },
  { country: "Sweden", iso: "se", code: "+46" },
  { country: "Switzerland", iso: "ch", code: "+41" },
  { country: "Syria", iso: "sy", code: "+963" },
  { country: "Taiwan", iso: "tw", code: "+886" },
  { country: "Tajikistan", iso: "tj", code: "+992" },
  { country: "Tanzania", iso: "tz", code: "+255" },
  { country: "Thailand", iso: "th", code: "+66" },
  { country: "Togo", iso: "tg", code: "+228" },
  { country: "Tokelau", iso: "tk", code: "+690" },
  { country: "Tonga", iso: "to", code: "+676" },
  { country: "Trinidad and Tobago", iso: "tt", code: "+1" },
  { country: "Tunisia", iso: "tn", code: "+216" },
  { country: "Turkey", iso: "tr", code: "+90" },
  { country: "Turkmenistan", iso: "tm", code: "+993" },
  { country: "Turks and Caicos Islands", iso: "tc", code: "+1" },
  { country: "Tuvalu", iso: "tv", code: "+688" },
  { country: "U.S. Virgin Islands", iso: "vi", code: "+1" },
  { country: "Uganda", iso: "ug", code: "+256" },
  { country: "Ukraine", iso: "ua", code: "+380" },
  { country: "United Arab Emirates", iso: "ae", code: "+971" },
  { country: "United Kingdom", iso: "gb", code: "+44" },
  { country: "United States Minor Outlying Islands", iso: "um", code: "+1" },
  { country: "United States", iso: "us", code: "+1" },
  { country: "Uruguay", iso: "uy", code: "+598" },
  { country: "Uzbekistan", iso: "uz", code: "+998" },
  { country: "Vanuatu", iso: "vu", code: "+678" },
  { country: "Vatican", iso: "va", code: "+379" },
  { country: "Venezuela", iso: "ve", code: "+58" },
  { country: "Vietnam", iso: "vn", code: "+84" },
  { country: "Wallis and Futuna", iso: "wf", code: "+681" },
  { country: "Western Sahara", iso: "eh", code: "+212" },
  { country: "Yemen", iso: "ye", code: "+967" },
  { country: "Zambia", iso: "zm", code: "+260" },
  { country: "Zimbabwe", iso: "zw", code: "+263" },
];
